### ISSUE TITLE
Data modeling: each column should have a default value.

### ISSUE THREAD

**Issue by cdhit** [Money-Manager-SaaS/mmss-backend#47]
`{"id":81,"transferType":-1,"amount":100,"note":null,"date":"2020-06-12T02:58:15.594Z","accountID":1,"toAccountID":null,"categoryID":1,"payeeID":null,"createdAt":"2020-06-12T02:59:01.377Z","updatedAt":"2020-06-12T02:59:01.377Z"},`

Took the above response from API for example. 
This response will cause a bug or needs more work from front-end.

**Comment by cdhit** [comment]
@kekakuka 

This is the root cause of the note.text.length.

**Comment by tim-hub** [comment]
no, this will no solve the problem.

if default value is set to ''

- null.test.length will throw error
- ''.text.length will throw error too

back-end is not a good place to fix this, the problem is this `note.text.length` which is not robust.

the solution should be `note && note.text ? note.text.length : 0` I believe Sanshi did this update this week.


Besides,

`an attribute should be null or a default value?`

from business side,
I think if it is optional, it can be null.

from dev side,
it has to be null, for example, toAccoundID is optional, you cannot set a default value to it. 0 or -1 is are not a really good solution.

above all, this issue should be created in front-end repo, the solution is to make the codes more robust, and I strongly disagree with set all attributes with a default value.
